name: Course Catalog

on:
  push:
    branch:
      - "master"
  pull_request:
    branch:
      - "master"
  workflow_dispatch: #manualmente

env:
  IMAGE_NAME: "course-catalog"
  IMAGE_TAG: "actions-0.${GITHUB_SHA}"
  IMAGE_TAG_LATEST: "latest"
  CONTAINER_IMAGE: "${{ IMAGE_NAME }}:${{ IMAGE_TAG }}"
  DOCKER_REGISTRY: "35.224.51.209:8082"
  HTTP_PROTO:  "http://"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build 
        run: docker build -t ${{ env.CONTAINER_IMAGE }} .

      - name: Unit Test      
        run: |
          docker run --rm -v "${{ github.workspace }}:/course-catalog/" ${{ env.CONTAINER_IMAGE }} \
            nosetests --with-xunit --with-coverage --cover-package=project test_users.py

