name: Course Catalog

on:
  push:
    branch:
      - "master"
  pull_request:
    branch:
      - "master"
  workflow_dispatch: #manualmente

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Build 
        run: docker build -t course-catalog:actions-0.${GITHUB_SHA} .

      - name: Unit Test      
        run: |
          docker run --rm -v "${{ github.workspace }}:/course-catalog/" course-catalog:actions-0.${GITHUB_SHA} \
            nosetests --with-xunit --with-coverage --cover-package=project test_users.py
